copypasta = [
    "cognione di merda ... ma lo vedi quanto sei ignorante e stupido ti fai ridere anche dietro dalle persone .. ma non ti vedi brutto stronzo ... vienimelo a dire in faccia a me o a @luche_official che non abbiamo diritto di parlare .. invece di fare il.leone dietro il cell tra una sega e l atra che fai dalla marina alla sera... vienilo a dircelo direttamente di persona .. sei talmente brutto che tua madre ti ha cagato nn partorito e vuoi parlare pure ... vieni vieni qua .. te lo dico",
    "cazzo fai obeso di merda pensi che bloccandomi riesci anche a bloccare i kg sulla bilancia che salgono ogni 2x3",
    "Gustoso primo piatto a base di funghi accompagnati da mezze penne rigate avvolte da una crema buonissima",
    "Credo che se calciavo i rigori con il cazzo tiravo meglio",
    "Dimmi qual'è il tuo vero nome che vengo sotto casa  tua e ti spacco la faccia a mazzate testa di cazzo",
    "Io quando vedo una zanzara la uccido pero non la distruggo la guardo mentre muore poi la distruggo ci sputo sopra e poi la calpesto ..credete sia abbastanza fidatevi lo faccio sul serio",
    "Scusate, vorrei lamentarmi di una cosa assurda che mi è successa oggi: sono andata al comune per chiedere informazioni su una futura apertura di uno studio veterinario. Mi hanno detto che serve LA LAUREA!!! Cioè è vergognoso che non basti la passione per gli animali per aprire uno studio veterinario!!!!",
    "E poi un'altra cosa pezzo di merda, quando fai le storie non fare l'accento napoletano perché io non ho mai sfottuto il vostro accento idiota di merda e poi seconda cosa io non dico in classifica stamm fort nel ritornello pisciazz quindi informati",
    "FIGAAAAAA assurda Topi Sexyssima sfondata vorrei girare scene con te e possibile",
    "vado a picchiare mia moglie e poi vado a dormire #carico",
    "le donne sono inutili",
    "se fossi donna farei la puttana",
    "Comunque tua mamma troglia",
    "Porcoddio se ce.lo dici a mia moglie  ti lancio 20 negri nudi puzolenti col.il cazzo di fuori",
    "Sapiamo.tutti che ate ci piace la minchia bella.calda",
    "Ciao a tutti a febbraio ho scoperto di essere in cinta perche mi a saltato il ciclo mi anno venuti la nausea il vomito ecc. Contenta lo detto subito al mio compango è lui era felicissimo in fatti al terzo mese di gravidanza mi a comprato la culla il passegino le tutine i pannolini il vasino il ciccio i giocattoli. Poi mi a venuto il ciclo è ha quel punto non c'è lo fatta ha dirglielo perche mi sentivo in colpa dopo tutti i soldi che a speso. So che non si dovrebbe fare ma li ho mostrato una finta ecografia di mia cuggina mi metto i cuscini sotto i vestiti x creare il pancione è fingo i crampi ogni tanto. Adesso dovrei essere al ottavo mese di gravidanza è sto cercando idee x simulare il parto. X la bambina o pensato di comprare una bambola reborn. Consigli su come inscenare un parto piu vero simile possibile? Grazie.",
    "io sono napoletana e nn é vero che a Napoli rubano tutta Italia lo pensa perché é invidiosa della nostra bellissima terra piena di luce e gioia .Come mai di Milano o di Venezia o Roma città dell' nord nn si parla mai perché di napoli si poi tutte bugie",
    "in seguito ai continui insulti (da parte vostra) ho deciso di proseguire in vie legali, verrete querelati  al tribunale di Catanzaro (Via Argento, 88100 Catanzaro CZ) con l'accusa si cyberbullismo, sono state registrate tutte le conversazioni con relative prove tra cui screenshot e video dei vari sfottò, mi sono già messo in contatto con il ministero della giustizia (Antonio Chiefalo) per la stesura dei documenti di denuncia."
]